### ISSUE TITLE
Purchase price and reporting by it and stock balance

### ISSUE THREAD

**Issue by emaijala** [emaijala/MLInvoice#112]
Add support for products to include purchase price and add a report for stock worth (purchase price * stock balance). Depends on #111.

**Comment by rulex** [comment]
@emaijala is there any reason why you put *purchase_price* in the *product* table?

Wouldn't it be much nicer to have it in *stock_balance_log*?

**Comment by emaijala** [comment]
It's done by the specs from an influential client, and the idea is to be able to use it to determine the value of a single item or the full stock. In this case the price at the time of stock balance change is not really meaningful. Additionally it's possible for a stock balance change to be negative. in that case having a purchase price there wouldn't make sense.
