### ISSUE TITLE
Add BuyerOrganisationTaxCode to Finvoice printer

### ISSUE THREAD

**Issue by aksl** [emaijala/MLInvoice#140]
Finvoice data should contain recipient VAT number in BuyerOrganisationTaxCode (or InvoiceRecipientOrganisationTaxCode). The VAT number is used in invoice transmission.

The addition could be done with adding this to invoice.php:
````
if (!empty($recipientData['company_id'])) {
  $recipientData['vat_id'] = createVATID($recipientData['company_id']);
} else {
  $recipientData['vat_id'] = '';
}
````
And this to create_finvoice.xsl after BuyerOrganisationName -element:
````
    <xsl:if test="vat_id!=''">
      <BuyerOrganisationTaxCode><xsl:value-of select="vat_id"/></BuyerOrganisationTaxCode>
    </xsl:if>
````

Testing can be done at Maventa, with the "test invoice XML data" function.
More details about the usage of fields at Maventa:
http://maventa.com/maventa-api/advansed/finvoice-parsing-finnish-users/

**Comment by emaijala** [comment]
Thanks, fixed!
