### ISSUE TITLE
Two configuration fields need to be translatable

### ISSUE THREAD

**Issue by ronnqvist** [emaijala/MLInvoice#216]
The content of the following settings will show up on any invoice regardless of the language. These fields are not translatable, which means that the word "days" ("päivää" in Finnish) for example would show up untranslated even though the rest of the invoices are perfectly translated.

Terms of payment (%d = payment days)
Period for complaints 

in Finnish:
Maksuehdot (%d = maksuaika päivinä)
Huomautusaika

**Comment by ronnqvist** [comment]
One possible solution would be to move these configurations under the company profile. I have separate company profiles configured depending on language, to get streetnames, e-mail messages, etc. in different languages. This is sort of a workaround, but it works really well.

**Comment by emaijala** [comment]
Note: Terms of payment in client data will continue to override the one in sender's fields.

**Comment by emaijala** [comment]
They are now in company profile but the general settings are still available and used as defaults.
