### ISSUE TITLE
Invoice numbering restarted from 100, overwriting old invoices!

### ISSUE THREAD

**Issue by ronnqvist** [emaijala/MLInvoice#217]
For some reason a new invoice got the number 100, the next 101, and so on overwriting old invoices! Don't know what caused this, but I can provide an SQL dump privately if you need to investigate.

**Comment by emaijala** [comment]
You do't have the setting to restart numbering every year on by any chance?

**Comment by ronnqvist** [comment]
No I don't, but now I noticed it happened when I changed company profile. (I use different profiles for different languages, to get different e-mail messages and addresses.)

**Comment by ronnqvist** [comment]
It may well be that it didn't overwrite any invoices after all, I might have mistaken an archived invoice for overwritten.

**Comment by emaijala** [comment]
You seem to have the setting "Separate invoice numbering per billing company" enabled. This means every company has its own invoice number sequence. If you want to have multiple companies share the sequence, disable that setting.
