### ISSUE TITLE
Finvoice printout causes 500 Internal server error

### ISSUE THREAD

**Issue by mitrpaka** [emaijala/MLInvoice#233]
Unable to printout invoices using finvoice with 1.14.2 version - request causes 500 Internal server error

GET request sent xx/mlinvoice/invoice.php?id=98&template=7&func=open_invoices with query params:
id=98
template=7
func=open_invoices

No response returned, only 500 error.

Most propably missing some php librray, using php 7.1.x

**Comment by mitrpaka** [comment]
php_xsl extension was missing ... Maybe we could add following check at the beginning of  printInvoice() method:

```
if (!extension_loaded('xsl') || !@class_exists('XSLTProcessor')) {
    $error = 'Could not load PHP XSL extension. Installing the PHP XSL extension is easy, please contact your server administrator to install libxslt.';
    echo $error;
} 
```

**Comment by emaijala** [comment]
That's a good idea. The requirement is mentioned in the installation instructions, but that's easy to miss.
