### ISSUE TITLE
Sähköpostiviestin sisältö puuttuu tai näkyy virheellisesti

### ISSUE THREAD

**Issue by perohen** [emaijala/MLInvoice#234]
Hei,

olen määrittänyt MLInvoicen lähettämään sähköpostit SparkPostin SMTP-palvelimen kautta (en tiedä johtuuko vika siitä, mutta mainitsen varmuuden vuoksi). Sähköpostit lähtevät normaalisti, mutta osa sähköpostiohjelmista näyttää viestit väärin. Tässä muutamia esimerkkejä testaamistani sähköpostipalveluista/-ohjelmista:
- Mozilla Thunderbird näyttää viestit oikein.
- FastMail näyttää viestien alussa "This is a multipart message in mime format." -tekstin, mutta sisältö on muuten normaali.
- Live.com-sähköposti ei näytä sähköpostin sisältöä ollenkaan vaan ainoastaan "This is a multipart message in mime format." -tekstin ja merkitsee viestin siksi roskapostiksi. Liitetiedosto on kuitenkin mukana.

Lähetetyn viestin lähdekoodi näyttää esimerkiksi seuraavalta (jätin liitteen PDF:n lähdekoodin pois):
```
--_=_swift_v4_1491405930_eed297941f371dffd021920483a0515a_=_
Content-Type: multipart/alternative;
 boundary="_=_swift_v4_1491405932_937ed9d09544af3bc74eb43127f9309e_=_"


--_=_swift_v4_1491405932_937ed9d09544af3bc74eb43127f9309e_=_
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

This is a multipart message in mime format.


--_=_swift_v4_1491405932_937ed9d09544af3bc74eb43127f9309e_=_
Content-Type: text/plain; charset=UTF-8; format="flowed"; charset=utf-8
Content-Transfer-Encoding: quoted-printable

Hei,

Ohessa on lasku PDF-muodossa. T=C3=A4m=C3=A4 on j=C3=A4rjestelm=
=C3=A4st=C3=A4=20
automaattisesti l=C3=A4hetetty
viesti, johon voi kuiten=
kin vastata, jos laskusta on kysytt=C3=A4v=C3=A4=C3=A4=20
tai huomautettava=
a.

Voitte maksaa laskun suoraan alla olevilla tiedoilla. K=C3=A4ytt=
=C3=A4k=C3=A4=C3=A4=20
aina viitenumeroa maksaessanne.

     Laskunumer=
o: 100
     Maksun saaja: XXXXXXXXXXXXXXXXX
     Tilinumero: FI24 XXXX =
XXXX XXXX XX
     BIC/SWIFT: NDEAFIHH
     Maksettava: 189,99 EUR
   =
  Viitenumero: 1009

Voitte maksaa laskun helposti verkkopankissa k=
=C3=A4ytt=C3=A4m=C3=A4ll=C3=A4=20
virtuaaliviivakoodia=20
XXXXXXXXXXXXXXXXX=
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Lasku on maksettava viimeist=
=C3=A4=C3=A4n er=C3=A4p=C3=A4iv=C3=A4n=C3=A4 05.04.2017.


--_=_swift_v4_1491405932_937ed9d09544af3bc74eb43127f9309e_=_--


--_=_swift_v4_1491405930_eed297941f371dffd021920483a0515a_=_
Content-Type: application/pdf; name=lasku_100.pdf
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=lasku_100.pdf

(Tässä olisi PDF:n lähdekoodi)

--_=_swift_v4_1491405930_eed297941f371dffd021920483a0515a_=_--
```

**Comment by emaijala** [comment]
Virhehän siinä on, pistetään korjaukseen seuraavaan versioon.

**Comment by emaijala** [comment]
Voisitko testata tällä versiolla: https://raw.githubusercontent.com/emaijala/MLInvoice/650c530fdf1a05efb6888de3e271c301ecf6dfa2/invoice_printer_email_trait.php
?
Omassa testissäni meni Outlookissa roskapostiin aika helposti, mutta ainakin viestin sisällön pitäisi näkyä oikein. Se voi olla aika tarkka siitä, mitä kautta viestit on lähetetty.

**Comment by perohen** [comment]
Riittääkö, jos testatessa korvaan nykyisen invoice_printer_email_trait.php-tiedoston tuolla?

**Comment by emaijala** [comment]
Kyllä pitäisi riittää.

**Comment by perohen** [comment]
Kiitos paljon avusta ja hyvästä ohjelmasta! Nyt viestien sisällöt toimivat odotetusti. Jostain syystä Hotmail merkitsee vieläkin viestin roskapostiksi, mutta se tuskin johtuu MLInvoicesta.

**Comment by emaijala** [comment]
Viestin headereista voisi saada jotain osviittaa siihen, miksi näin käy. Syitä voi olla vaikka kuinka paljon..
