### ISSUE TITLE
Finvoice printout causes 500 Internal server error (v1.15.4)

### ISSUE THREAD

**Issue by mitrpaka** [emaijala/MLInvoice#259]
Error log:

`[10-Sep-2017 21:26:10 Europe/Helsinki] PHP Warning:  SimpleXMLElement::addChild(): Element name is required in xxx/MLInvoice/invoice_printer_xslt.php on line 157`
`[10-Sep-2017 21:26:10 Europe/Helsinki] PHP Fatal error:  Uncaught Error: Call to a member function addChild() on null in xxx/MLInvoice/invoice_printer_xslt.php:162`
`Stack trace:`
`#0 xxx/MLInvoice/invoice_printer_xslt.php(158): InvoicePrinterXslt->arrayToXML(Array, NULL)`
`#1 xxx/MLInvoice/invoice_printer_xslt.php(155): InvoicePrinterXslt->arrayToXML(Array, Object(SimpleXMLElement))`
`#2 xxx/MLInvoice/invoice_printer_xslt.php(62): InvoicePrinterXslt->arrayToXML(Array, Object(SimpleXMLElement))`
`#3 xxx/MLInvoice/invoice_printer_finvoice.php(26): InvoicePrinterXslt->transform('create_finvoice...', 'Finvoice.xsd')`
`#4 xxx/MLInvoice/invoice.php(134): InvoicePrinterFinvoice->printInvoice()`
`#5 {main}
  thrown in xxx/MLInvoice/invoice_printer_xslt.php on line 162`

Does work with v1.15.3, but not with v1.15.4 Regression from VAT summary sorting?

**Comment by emaijala** [comment]
Can you try with the latest invoice_printer_xslt.php here: https://raw.githubusercontent.com/emaijala/MLInvoice/master/invoice_printer_xslt.php ? Thanks!

**Comment by mitrpaka** [comment]
Did test it with the latest invoice_printer_xslt.php and now it works! Thank you for quick reply and fix!

Will close the issue.
