### ISSUE TITLE
Add support for repeating invoices

### ISSUE THREAD

**Issue by emaijala** [emaijala/MLInvoice#28]
Add support for invoices that repeat once a month or year. It should be possible to select the interval and next invoice date. Then the system should notify user when there are invoices due for processing.

Related to issue #4, which would automate the processing.

**Comment by ronnqvist** [comment]
Until possibility to select the more precise interval is implemented, one or two options between yearly and monthly would be good. Quarterly I'd need personally, and some might want bi-annually as well.

**Comment by emaijala** [comment]
There are already more options in the master version.
