### ISSUE TITLE
Add customer invoice listing context when viewing an invoice

### ISSUE THREAD

**Issue by mtchetch** [emaijala/MLInvoice#382]
It would be useful to be able to directly open a list of customers previous invoices when viewing an existing invoice. This is a thing I often do when invoicing.

The feature could be a simple link that would open a search list filtered to the ID of the customer for the opened invoice.

![mlinvoice](https://user-images.githubusercontent.com/11362763/196162378-e3feed46-a716-431e-a4f0-ab33ec768885.png)

**Comment by emaijala** [comment]
Good idea. I'll think about the implementation a bit. A new button in addition to the existing two client-related ones (info and "Add new") is pushing it a bit, but perhaps some of this could be combined into a dropdown or something.

**Comment by emaijala** [comment]
@mtchetch While it's not as direct a route as your proposal, I've now added a button to display all of customer's invoices (and offers) on the customer information screen. So you'll need two clicks from the invoice screen, but at least it's now possible.

**Comment by mtchetch** [comment]
This is an ok compromise and the issue can be vlosed
