### ISSUE TITLE
Postita API sends finvoices using only OVT - This is problematic because companies change Intermediators

### ISSUE THREAD

**Issue by mtchetch** [emaijala/MLInvoice#387]
I have been using the Postita integration for a few years (thanks for implementing it when we asked a few years ago).

Every so often, we run into issues with invoices not going through to the recipient. There is no error message and the system (both MLinvoice and Postita.fi) show the invoice as being sent successfully.

The issue lies with the open catalogue data for e-invoice recipients not updating quickly enough and the invoices being sent using the wrong intermediators and getting either delivered to a system that is no longer being used or lost completely.

In MLinvoice there are fields for the intermediator in customer details, but while debugging the problem, these do not seem to be used in the API.

Invoices sent with only the OVT address of the company will experience delivery problems if the receiver changes their finance system, which often leads to a different intermediator being used.

Would it be possible to upgrade Postita API to use the intermediator value from customer information, since there is a field for it?

On a happy sidenote, I have used MLinvoice (and its predecessors before you took over development) to send 3865 invoices all the way from 2010.

**Comment by emaijala** [comment]
I'll take a look. If the API supports it, there should be no problem actually using it.

**Comment by mtchetch** [comment]
Tested this with postita API. It seemed to work, but no real way to tell if the system uses the intermediator ID or not. 

This should be implemented in the next version so that all the existing fields get passed along to the invoice sender. On a side note the sending company needs to have the ID numbers too in order to send invoices.
