### ISSUE TITLE
select2 module does not install with composer install and is missing from git V2.1.0 branch

### ISSUE THREAD

**Issue by mtchetch** [emaijala/MLInvoice#390]
When setting up mlinvoice with git from V2.1.0 branch select2 dependency does not install to node_modules/ folder automatically. It is in your release zip file but not in git and it does not get downloaded with composer install.

The missing library breaks all listings.

**Comment by emaijala** [comment]
True, you'll need to run `npm install --production` as well. I've updated the instructions on the web pages to indicate that. Thanks!
