### ISSUE TITLE
2.1 rc4 - When editing invoice rows the selected product gets set to empty upon edit

### ISSUE THREAD

**Issue by mtchetch** [emaijala/MLInvoice#391]
![image](https://user-images.githubusercontent.com/11362763/220574433-0ca614bb-1363-483e-a437-f3f7a1f6a39f.png)

It also seems to remember the last selected product and can unintentionally either remove products from edited rows or set them to an incorrect value when first editing a row and then editing another row.

**Comment by emaijala** [comment]
Fixed for 2.1.
