### ISSUE TITLE
2.1 RC4 - When clicking the product field on new row the search field does not activate and search does not work when typing

### ISSUE THREAD

**Issue by mtchetch** [emaijala/MLInvoice#392]
![image](https://user-images.githubusercontent.com/11362763/220574999-48d456b4-9b8b-4244-91a5-4c978be3c200.png)

When clicking the product field on the new row form the search autocomplete field should be set active automatically with out the need to first click the product box and then click the autocomplere search field.

![image](https://user-images.githubusercontent.com/11362763/220575271-1c061ddd-042a-492b-a4e8-26c5825960ea.png)

**Comment by emaijala** [comment]
Thanks for reporting this. Seems to be an odd issue with the new Select2 version. I'll add a workaround for it.
