### ISSUE TITLE
Customer contextual filtering not filtering by customer and returning all results

### ISSUE THREAD

**Issue by mtchetch** [emaijala/MLInvoice#410]
git status
On branch release-2.2
Your branch is up to date with 'origin/release-2.2'.

When opening an invoice, opening the customer information via the customer link (Asiakas) and selecting show all invoices the list does not get filtered.

![image](https://github.com/user-attachments/assets/6f706aaa-1641-4a0e-8cce-942796b98f63)

The listing returns all invoices that are in the system

![image](https://github.com/user-attachments/assets/f7fa820e-15a4-4964-ae52-d1655008ba2b)

The url produced is: https://mlinvoice.mydomain.fi/index.php?func=results&search_id=-5&s_type1[]=company_id&s_field1[]=694 where 694 does match the company ID that should be filtered by.

When selecting edit search the edit screen has blank customer

![image](https://github.com/user-attachments/assets/a4f7fe26-eb11-47a6-801a-c9dd1e2b828c)

If the blank customer is replaced with the customer that should be filtered by the view works as expected and produces a result table with only the selected customer.

the url for the edited search is: https://mlinvoice.mydomain.fi/index.php?func=results&type=invoice&s_op=AND&s_op1=OR&s_type1%5B%5D=state_id&s_cmp1%5B%5D=eq&s_field1%5B%5D=1&s_type1%5B%5D=state_id&s_cmp1%5B%5D=eq&s_field1%5B%5D=2&s_type1%5B%5D=state_id&s_cmp1%5B%5D=eq&s_field1%5B%5D=3&s_type1%5B%5D=state_id&s_cmp1%5B%5D=eq&s_field1%5B%5D=4&s_type1%5B%5D=state_id&s_cmp1%5B%5D=eq&s_field1%5B%5D=5&s_type1%5B%5D=state_id&s_cmp1%5B%5D=eq&s_field1%5B%5D=6&s_type1%5B%5D=state_id&s_cmp1%5B%5D=eq&s_field1%5B%5D=7&s_type1%5B%5D=state_id&s_cmp1%5B%5D=eq&s_field1%5B%5D=8&s_type1%5B%5D=state_id&s_cmp1%5B%5D=eq&s_field1%5B%5D=9&s_op2=AND&s_type2%5B%5D=archived&s_cmp2%5B%5D=eq&s_field2%5B%5D=0&s_op3=AND&s_type3%5B%5D=company_id&s_cmp3%5B%5D=eq&s_field3%5B%5D=694

**Comment by emaijala** [comment]
Thanks for the thorough report. I'll make sure this gets fixed in the next bug fix release.
